services:
  postgres-test:
    image: postgres:16
    container_name: postgres-test
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - troc-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_TEST} -d ${POSTGRES_DB_TEST}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    build: .
    container_name: spring-boot-test
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-test:5432/${POSTGRES_DB_TEST}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER_TEST}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "8081:8080"
    networks:
      - troc-test-network

networks:
  troc-test-network:
    driver: bridge

volumes:
  postgres_test_data: