spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_DB}_test
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  flyway:
    enabled: false